### PR TITLE
[ricos-theme] improve bundleSize - JSS plugins

### PR DESCRIPTION
**Pull request by Barackos**
### Before
(included in `jss-preset-default`)

    "jss": "^10.1.1",
    "jss-plugin-camel-case": "^10.1.1",
    "jss-plugin-compose": "^10.1.1",
    "jss-plugin-default-unit": "^10.1.1",
    "jss-plugin-expand": "^10.1.1",
    "jss-plugin-extend": "^10.1.1",
    "jss-plugin-global": "^10.1.1",
    "jss-plugin-nested": "^10.1.1",
    "jss-plugin-props-sort": "^10.1.1",
    "jss-plugin-rule-value-function": "^10.1.1",
    "jss-plugin-rule-value-observable": "^10.1.1",
    "jss-plugin-template": "^10.1.1",
    "jss-plugin-vendor-prefixer": "^10.1.1"

### After
	"jss": "^10.4.0",
    "jss-plugin-camel-case": "^10.4.0",
    "jss-plugin-props-sort": "^10.4.0",
    "jss-plugin-nested": "^10.4.0",

### CODE REVIEW

**Comment by Barackos** [comment]
@oded-soffrin @mharsat @lxgreen What a significant change in bundle size :)
We might as well remove [jss-plugin-props-sort](https://cssinjs.org/jss-plugin-props-sort?v=v10.4.0) but it feels safe to keep it.

**Comment by oded-soffrin** [comment]
Amazing!
I don't want to crap on the parade but the improvements are due to making theme strategy opt-in. (i forgot to update bundle sizes once I've merged my branch - https://github.com/wix-incubator/rich-content/pull/1500)

in order to measure the change we need to define a new bundle the imports ricos-theme.
I bet it's about 5KB gzipped which is plenty

**Comment by lxgreen** [comment]
@oded-soffrin please wait with baseline update, I want this beautiful report for my plugin-commons PR

**Comment by oded-soffrin** [comment]
@Barackos added the measurement to master, and ran it here - https://github.com/wix-incubator/rich-content/pull/1518
(not sure if bundle analyzer runs again on the same branch, you can merge from master and see if you get the same results)

**Review by oded-soffrin — APPROVED** [review]

**Review by mharsat — APPROVED** [review]
Clever optimization!

**Pull request merged**
