### PR TITLE
saveStateInLocalStorage

### PR DESCRIPTION
**Pull request by shaulgo**

### CODE REVIEW

**Comment by shaulgo** [comment]
I'm pretty sure it wasn't working correctly. And I wanted to change it.

**Comment by oded-soffrin** [comment]
This should be a major improvement for dev velocity - @shaulgo what needs to be changed?

**Comment by shaulgo** [comment]
Seems like I have much more time to program now. I'll fix it

**Comment by oded-soffrin** [comment]
@shaulgo  ?

**Comment by oded-soffrin** [comment]
Resolved by @shaulgo overhaul of example app

**Pull request closed without merging**
