### PR TITLE
[translatitons] reduce viewer bundle size

### PR DESCRIPTION
**Pull request by oded-soffrin**

### CODE REVIEW

**Comment by oded-soffrin** [comment]
@lxgreen @shaulgo this is the first try of splitting the translations files

currently we have 3 locations:
common/statics/locle - has all translations for backward compatibility
common/statics/viewer/locale - only viewer keys
editor-common/statics/locale - only editor keys

reduces about 30kb for all viewer bundles (!)
test fails for some reason though, still investigating

**Comment by oded-soffrin** [comment]
Fails on any branch https://github.com/wix-incubator/rich-content/pull/1734

**Comment by shaulgo** [comment]
YAAAA :)
Is there a way to measure the effect on our TPA?

**Comment by oded-soffrin** [comment]
@shaulgo yes we can compare it to perfer and to LH score once we can merge
The problem is all the tests are failing now on master for unknown reasons

**Pull request closed without merging**
